name: Hello World Workflow

# Trigger the workflow on every push to the main branch, or manually
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run a one-line script
        run: echo "Hello, World!"